# Generated by Django 4.0.6 on 2022-09-16 23:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('country', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=40, null=True)),
                ('mode', models.CharField(choices=[('DMR', 'DMR'), ('SSB', 'SSB'), ('CW', 'CW'), ('AM', 'AM'), ('FM', 'FM'), ('RTTY', 'RTTY'), ('FT8', 'FT8'), ('SSTV', 'SSTV'), ('C4FM', 'C4FM'), ('JS8', 'JS8'), ('FT4', 'FT4'), ('PSK31', 'PSK31'), ('DSTAR', 'DSTAR'), ('SSB', 'SSB')], default='AM', max_length=10)),
                ('power', models.IntegerField(max_length=4)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 9, 16, 23, 38, 53, 719405, tzinfo=utc))),
            ],
        ),
    ]
